#!/bin/bash

set -e

source config.sh

array_size=$(wc -l $LIBRARIES_LIST)

bash steps/0-prepare-scratch.bash

giraffe_job_id=$(sbatch \
    -a 1-${array_size} \
    --clusters $CLUSTER \
    -p $PARTITION \
    --cpus-per-task $GIRAFFE_CPUS \
    --mem $GIRAFFE_MEM \
    -t $GIRAFFE_TIME \
    -o logs/giraffe.%a.out \
    -e logs/giraffe.%a.err \
    --parseable \
    steps/1-giraffe-align.slurm \
    | sed 's/;.\+$//')

surject_job_id=$(sbatch \
    -a 1-${array_size} \
    --clusters $CLUSTER \
    -p $PARTITION \
    --cpus-per-task $SURJECT_CPUS \
    --mem $SURJECT_MEM \
    -t $SURJECT_TIME \
    -o $OUT_DIR/logs/surject.%a.out \
    -e $OUT_DIR/logs/surject.%a.err \
    --dependendy=aftercorr:${giraffe_task_id}
    steps/2-surject.slurm \
    | sed 's/;.\+$//')
