#!/bin/bash

set -e

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source $SCRIPT_DIR/config.sh

array_size=$(wc -l < $LIBRARIES_LIST)

echo "Copying files to scratch..."
bash $SCRIPT_DIR/steps/0-prepare-scratch.bash

mkdir -p $OUT_DIR/logs

echo "Submitting jobs..."
giraffe_job_id=$(sbatch \
    -a 1-${array_size} \
    --clusters $CLUSTER \
    -p $PARTITION \
    --cpus-per-task $GIRAFFE_CPUS \
    --mem $GIRAFFE_MEM \
    -t $GIRAFFE_TIME \
    -o $OUT_DIR/logs/giraffe.%a.out \
    -e $OUT_DIR/logs/giraffe.%a.err \
    --parsable \
    $SCRIPT_DIR/steps/1-giraffe-align.slurm \
    | sed 's/;.\+$//')
echo "Submitted job ${giraffe_job_id}."

surject_job_id=$(sbatch \
    -a 1-${array_size} \
    --clusters $CLUSTER \
    -p $PARTITION \
    --cpus-per-task $SURJECT_CPUS \
    --mem $SURJECT_MEM \
    -t $SURJECT_TIME \
    -o $OUT_DIR/logs/surject.%a.out \
    -e $OUT_DIR/logs/surject.%a.err \
    --dependency=aftercorr:${giraffe_task_id} \
    --parsable \
    $SCRIPT_DIR/steps/2-surject.slurm \
    | sed 's/;.\+$//')

echo "Done submitting jobs."
